id: I28D660A2
legacy_id: P004362
ocr_import_info:
  bdrc_scan_id: W1KG23667
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T05:09:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:25:32.842058+00:00'
last_modified: 2022-08-27 15:25:54.978080
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23667
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23667
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གནས་བརྟན་ཕྱག་མཆོད་སོགས་ཆོ་གའི་རིམ་པ་འགའ་ཞིག
statistics:
  ocr_word_mean_confidence_index: 0.957550422618813
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG23774:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23774
      total_pages: 206
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG23774.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.957550422618813
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
