id: P004362
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:14:58.115064
source_metadata:
  id: bdr:W1KG23667
  title: གནས་བརྟན་ཕྱག་མཆོད་སོགས་ཆོ་གའི་རིམ་པ་འགའ་ཞིག
  author: ''
  volumes:
    f99d90cbca8f4514975449a5d35b3f9c:
      image_group_id: I1KG23774
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
