id: P004362
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23667
  title: གནས་བརྟན་ཕྱག་མཆོད་སོགས་ཆོ་གའི་རིམ་པ་འགའ་ཞིག
  author: ''
  volumes:
    f99d90cbca8f4514975449a5d35b3f9c:
      image_group_id: I1KG23774
      title: ''
      volume_number: 1
      total_pages: 206
      base_file: v001.txt
